version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/collections"]
      interval: 5s
      timeout: 3s
      retries: 10

  embeddings-loader:
    build: ./embeddings-loader
    depends_on:
      qdrant:
        condition: service_healthy
    volumes:
      - ./embeddings-data/embeddings.json:/app/embeddings.json
    environment:
      - QDRANT_HOST=qdrant
    command: ["python", "load_embeddings.py"]
