name: rag_dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - jupyterlab
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - tqdm
  - sentence-transformers
  - pip:
      - qdrant-client
      - pdfminer.six==20221105